version: '3.8'

services:
  # PHP Application
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
      target: dev
      args:
        WWWUSER: ${WWWUSER:-1000}
        WWWGROUP: ${WWWGROUP:-1000}
    restart: always
    container_name: ArSysMobile-app
    working_dir: /var/www
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - redis
    networks:
      - webFPTE # Menghubungkan ke network bersama

  nginx:
    image: nginx:alpine
    container_name: ArSysMobile-nginx
    restart: always
    ports:
      - "8081:80"
    volumes:
      - .:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - webFPTE

  redis:
    image: redis:alpine
    container_name: ArSysMobile-redis
    restart: always
    networks:
      - webFPTE

networks:
  webFPTE:
    external: true # Memberitahu docker ini network yang sudah ada di luar file ini
